---
# NOTES
# -----
# systemd-networkd is here setup to automatically use systemd-resolved

- name: systemd-networkd role
  tags:
    - systemd-networkd
  block:

  # systemd_networkd.state
  - when: systemd_networkd.state == "enabled"
    block:

    # NetworkManager
    - name: Stop & disable NetworkManager.service
      become: true
      ansible.builtin.systemd_service:
        name: NetworkManager.service
        state: stopped
        enabled: false

    # systemd-networkd.service
    - name: Start & enable systemd-networkd.service
      become: true
      ansible.builtin.systemd_service:
        name: systemd-networkd.service
        state: started
        enabled: true

    # systemd-resolved
    - name: Start & enable systemd-resolved.service
      become: true
      ansible.builtin.systemd_service:
        name: systemd-resolved.service
        state: started
        enabled: true

    # stat etc resolv.conf
    - name: Stat /etc/resolv.conf
      become: true
      ansible.builtin.stat:
        path: /etc/resolv.conf
      register: _etc_resolv

    # stat systemd resolv.conf
    - name: Stat /run/systemd/resolve/resolv.conf
      become: true
      ansible.builtin.stat:
        path: /run/systemd/resolve/resolv.conf
      register: _systemd_resolv

    - when: 
      - _systemd_resolv.stat.exists == true
      - _etc_resolv.stat.lnk_target != "/run/systemd/resolve/resolv.conf"
      block:

      # cp
      - name: Backup /etc/resolv.conf
        become: true
        ansible.builtin.copy:
          src: /etc/resolv.conf
          dest: /etc/resolv.conf.backup
          
      # rm
      - name: Remove /etc/resolv.conf
        become: true
        ansible.builtin.file:
          path: /etc/resolv.conf
          state: absent

      # link
      - name: Link /run/systemd/resolve/resolv.conf to /etc/resolv.conf
        become: true
        ansible.builtin.file:
          src: /run/systemd/resolve/resolv.conf
          dest: /etc/resolv.conf
          state: link

  # mkdir
  - name: Mkdir /etc/systemd/network
    ansible.builtin.file:
      path: /etc/systemd/network
      state: directory
      owner: root
      group: root
      mode: o=rwx,g=rx,o=rx

  # cp config
  - when: systemd_networkd.config.files.cp | length > 0
    block:
    
    # cp
    - name: Copy config files {{ systemd_networkd.config.files.cp }}
      become: true
      loop: "{{ systemd_networkd.config.files.cp }}"
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /etc/systemd/network/

  # rm config
  - when: systemd_networkd.config.files.rm | length > 0
    block:
    
    # rm
    - name: Remove config files {{ systemd_networkd.config.files.rm }}
      become: true
      loop: "{{ systemd_networkd.config.files.rm }}"
      ansible.builtin.file:
        path: "/etc/systemd/network/{{ item }}"
        state: absent
